# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1syrp1-I876X0azETmOpXhku0ocaMxQ09
"""

import pandas as pd
data=pd.read_csv("sample_data/hepatitis_csv.csv")
data
from numpy import percentile
Minimum, Maximum = data.min(), data.max()
print(Minimum)
print(Maximum)
import statistics as st
import matplotlib.pyplot as plt
data.plot(figsize=(15,8))
plt.legend()
plt.grid()
plt.show()
data['age'].dropna()
plt.hist(data['age'], bins = 5)
data.describe()
data.info()
import seaborn as sns
plt.figure(figsize=(12,12))
sns.heatmap(data.corr(),cmap='Oranges',annot=False)
plt.show()
sns.countplot(x='class', data=data, hue='class')
plt.show()
sns.countplot(x='sex', data=data, hue='sex')
plt.show()